document.write('<OBJECT id=XRapidView style="LEFT:0px; TOP:0px" width="100%" height="100%"');
document.write('classid="clsid:7E35572C-CFA3-44FB-B6DC-F06CCEFEBAE0">');
document.write('	<PARAM NAME="Serialize" VALUE=1>			<!-- 사용자 설정 값을 레지스트리 기록 및 사용 여부 -->');
document.write('												<!--');
document.write('												0 : X');
document.write('												1 : O(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="UIMode" VALUE=15>				<!-- UIMode :');
document.write('												UIMODE_MENU = 1,(기본값)');
document.write('												UIMODE_TOOLBAR = 2,(기본값)');
document.write('												UIMODE_STATUSBAR = 4,(기본값)');
document.write('												UIMODE_POPUP = 8(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="OldToolbar" VALUE=1>			<!-- OldToolbar :');
document.write('												OldToolbar 값이 1이면 ocx 자체에 Toolbar가 생기고 Old Toolbar 값이 0이면 상위 컨테이너에 Toolbar가 생김');
document.write('												하이퍼링크등의 인터페이스 화면에서 툴바 껌벅거림이 보기 싫을 때 1로 사용하면 좋음.');
document.write('												0 : 컨테이너에 툴바 생성');
document.write('												1 : ocx 자체에 툴바 생성(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="HasPrintDlg" VALUE=1>			<!-- 인쇄시 인쇄 설정 창을 보여줄지 여부(0 : 안보여줌, 1 : 보여줌, 기본값 : 1) -->');
document.write('	<PARAM NAME="DirectPrintMode" VALUE=0>		<!-- 직접 인쇄시 인쇄 Mode(0 : 설정 창 설정 없이 인쇄, 1 : 설정 창 자동 설정, 기본값 : 0) -->');
document.write('	<PARAM NAME="HasFontDlg" VALUE=1>			<!-- Font가 없을 경우 Font 설정 창을 보여줄지 여부(0 : 안보여줌, 1 : 보여줌, 기본값 : 1) -->');
document.write('	<PARAM NAME="CursorStyle" VALUE=2>			<!-- CursorStyle :');
document.write('												CURSOR_NULL = 1,');
document.write('												CURSOR_ZOOM = 2,(기본값)');
document.write('												CURSOR_PAN = 3,');
document.write('												CURSOR_PICKER = 4,');
document.write('												CURSOR_RULER = 5,');
document.write('												CURSOR_ANGLE = 6,');
document.write('												CURSOR_AREA = 7,');
document.write('												MARKUP_LINE = 129,');
document.write('												MARKUP_ARROW = 130,');
document.write('												MARKUP_BOX = 131,');
document.write('												MARKUP_TEXTBOX = 132,');
document.write('												MARKUP_FREEHAND = 133,');
document.write('												MARKUP_CIRCLE = 134,');
document.write('												MARKUP_CLIP = 135,');
document.write('												MARKUP_CLOUD = 136,');
document.write('												MARKUP_LINK = 137,');
document.write('												-->');
document.write('	<PARAM NAME="PrintMode" VALUE=2>			<!-- PrintMode :');
document.write('												바코드 인쇄 안함 = 1,');
document.write('												바코드 인쇄 = 2');
document.write('												-->');
document.write('	<PARAM NAME="BarcodeType" VALUE=5>			<!-- BarcodeType :');
document.write('												CODE128 = 0,(기본값)');
document.write('												CODE39 = 1,');
document.write('												CODE93 = 2,');
document.write('												CODEBAR = 3,');
document.write('												I2OF5 = 4,');
document.write('												CODESTRING = 5');
document.write('												QRCODE = 6');
document.write('												-->');
document.write('	<PARAM NAME="BarcodeSubset" VALUE=1>		<!-- BarcodeSubset :');
document.write('												A = 0,');
document.write('												B = 1,(기본값)');
document.write('												C = 2');
document.write('												-->');
document.write('	<PARAM NAME="BarcodeColor" VALUE=1>					<!-- 0:미사용 1:사용 -->');
document.write('	<PARAM NAME="BarcodeDarkness" VALUE=0>				<!-- Barcode 진하기 설정, 0~255 사이의 값, 0 : 진함, 255 : 흐림, (기본값 : 0)-->');
document.write('	<PARAM NAME="BarcodeLeft" VALUE=0.03>				<!-- 0~1사이의 값(기본값 : 0.03) -->');
document.write('	<PARAM NAME="BarcodeTop" VALUE=0.97>				<!-- 0~1사이의 값(기본값 : 0.97) -->');
document.write('	<PARAM NAME="BarcodeLeft2" VALUE=0.03>				<!-- 0~1사이의 값(기본값 : 0.03) -->');
document.write('	<PARAM NAME="BarcodeTop2" VALUE=0.97>				<!-- 0~1사이의 값(기본값 : 0.97) -->');
document.write('	<PARAM NAME="BarcodeWidth" VALUE=0.001>				<!-- 0~1사이의 값(기본값 : 0.01) -->');
document.write('	<PARAM NAME="BarcodeHeight" VALUE=0.02>				<!-- 0~1사이의 값(기본값 : 0.02) -->');
document.write('	<PARAM NAME="BarcodeRatio" VALUE=0>');
document.write('	<PARAM NAME="Barcode" VALUE="Marked for Revision No. xxxx">		<!-- Barcode 문자열(기본값 : "OpenMinds XRapidView") -->');
document.write('	<PARAM NAME="Barcode2" VALUE="Marked for Revision No. xxxx">	<!-- Barcode 문자열(기본값 : "OpenMinds XRapidView") -->');
document.write('	<PARAM NAME="ShowWaterMark" VALUE=1>					<!-- WaterMark Display 여부-->');
document.write('															<!--');
document.write('															0 : X');
document.write('															1 : O(기본값)');
document.write('															-->');
document.write('	<PARAM NAME="ShowWaterMarkMain" VALUE=0>				<!-- WaterMark Display 여부-->');
document.write('															<!--');
document.write('															0 : X');
document.write('															1 : O(기본값)');
document.write('															-->');
document.write('	<PARAM NAME="WaterMarkLeft" VALUE=1000>					<!-- WaterMark Left값(기본값 : 0) -->');
document.write('	<PARAM NAME="WaterMarkTop" VALUE=200>					<!-- WaterMark Top값(기본값 : 0) -->');
document.write('	<PARAM NAME="WaterMarkType" VALUE=2>					<!-- WaterMarkType');
document.write('															0 : WaterMarkFontSize 크기의 Text를 반복하여 표시');
document.write('															1 : 용지 크기에 맞게 수평으로 한번만 표시');
document.write('															2 : 용지 크기에 맞게 사선으로 한번만 표시(기본값)');
document.write('															3 : WaterMarkImage 파일에 지정한 Image를 용지 크기에 맞게 수평으로 한번만 표시');
document.write('															4 : WaterMarkImage 파일에 지정한 Image를 용지 크기에 맞게 사선으로 한번만 표시(기본값)');
document.write('															5 : 용지 크기에 맞게 수평으로 3줄 표시');
document.write('															6 : 용지 크기에 맞게 사선으로 3줄 표시');
document.write('															7 : WaterMarkFontSize 크기의 Text를 WaterMarkLeft, WaterMarkTop 위치에 하나만 표시');
document.write('															8 : WaterMarkImage 파일에 지정한 Image를 용지 크기에 맞게 사선으로 여러개 표시');
document.write('															-->');
document.write('	<PARAM NAME="WaterMark" VALUE="XRapidView">				<!-- WaterMark 문자열(기본값 : "XRapidView")');
document.write('															"&"는 "&&"로 표시, ex) "Rush & Cash" ==> "Rush && Cash"');
document.write('															-->');
document.write('	<PARAM NAME="WaterMark2" VALUE="XRapidView211111\nsdfasd\nasdfas">				<!-- WaterMark 문자열(기본값 : "XRapidView")');
document.write('															"&"는 "&&"로 표시, ex) "Rush & Cash" ==> "Rush && Cash"');
document.write('															-->');
document.write('	<PARAM NAME="WaterMark3" VALUE="XRapidView3">			<!-- WaterMark 문자열(기본값 : "XRapidView")');
document.write('															"&"는 "&&"로 표시, ex) "Rush & Cash" ==> "Rush && Cash"');
document.write('															-->');
document.write('	<PARAM NAME="WaterMarkDarkness" VALUE=200>				<!-- WaterMark 진하기 설정');
document.write('															0~255 사이의 값');
document.write('															0 : 진함');
document.write('															255 : 흐림');
document.write('															(기본값 : 200)');
document.write('															-->');
document.write('	<PARAM NAME="WaterMarkFontSize" VALUE=80>				<!-- WaterMark Font 크기 설정(기본값 : 80) -->');
document.write('	<PARAM NAME="WaterMarkFontWeight" VALUE=1000>			<!-- WaterMark Font 두께 설정(0 ~ 1000, 값이 클수록 두꺼우며 0은 기본 두께, 기본값:1000) -->');
document.write('	<PARAM NAME="WaterMarkImage" VALUE="C:\\watermark.bmp">	<!-- WaterMarkImage 파일명(기본값 : "watermark.bmp") 미리보기필요시 "watermark_p.bmp" -->');
document.write('	<PARAM NAME="WaterMarkImageScale" VALUE=70>				<!-- WaterMarkImage를 용지 크기에 비례하여 확대/축소할 비율, 0 ~ 200 사이의 값(기본값 : 70) -->');
document.write('	<PARAM NAME="ShowCtlChar" VALUE="\\P">		<!-- TextObject 메서드에서 디스플레이 하고 싶은 텍스트 관련 프라퍼티');
document.write('												case "\\O":		// overscoring!');
document.write('												case "\\o":		// overscoring!');
document.write('												case "\\L":		// underscoring!');
document.write('												case "\\l":		// underscoring!');
document.write('												case "\\~":		// nonbreaking space!');
document.write('												case "\\\\":	// backslash!');
document.write('												case "\\{":		// opening brace!');
document.write('												case "\\}":		// closing brace!');
document.write('												case "\\C":		// color!');
document.write('												case "\\F":		// font file!');
document.write('												case "\\f":		// type face!');
document.write('												case "\\H":		// text height!');
document.write('												case "\\S":		// stacks at the \, #, ^');
document.write('												case "\\T":		// space between characters !');
document.write('												case "\\Q":		// oblique angle!');
document.write('												case "\\W":		// width factor!');
document.write('												case "\\A":		// alignment!');
document.write('												case "\\P":		// ends paragraph!');
document.write('												-->');
document.write('	<PARAM NAME="BackColor" VALUE=0>			<!-- 0x00bbggrr 값을 10진수로 변환한 값 -->');
document.write('	<PARAM NAME="HasPrintPriv" VALUE=1>			<!-- 인쇄 권한');
document.write('												0 : 인쇄 불가');
document.write('												1 : 인쇄 가능');
document.write('												-->');
document.write('	<PARAM NAME="HasMarkupPriv" VALUE=1>		<!-- 마크업 권한');
document.write('												0 : 마크업 불가');
document.write('												1 : 마크업 가능');
document.write('												-->');
document.write('	<PARAM NAME="ShowTopMenus" VALUE="111111">	<!-- 6개(파일, 보기, 도구, 마크업, 설정, 도움말)의 탑 메뉴 디스플레이 여부 설정.');
document.write('												체크 비트 :');
document.write('													0 = Hide,	1 = Show');
document.write('												탑메뉴 순서 :');
document.write('													파일, 보기, 도구, 마크업, 설정, 도움말');
document.write('												기본값 :');
document.write('													"111111" = 모든 탑 메뉴 디스플레이.');
document.write('												예 :');
document.write('													"011011". 파일과 마크업 메뉴는 숨기고 나머지 메뉴는 디스플레이');
document.write('												-->');
document.write('	<PARAM NAME="LoadImportedImage" VALUE=1>	<!-- DWG 파일에 Import 된 Image 디스플레이 여부 설정');
document.write('												0 : Image 안 보여주기');
document.write('												1 : Image 보여주기(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="SubstituteFont" VALUE="">		<!-- 대체 Font 설정 -->');
document.write('	<PARAM NAME="ExtendCombineImage" VALUE=2>	<!-- Combine 도면의 image size를 dwg size에 맞춰서 확대/축소할지 여부');
document.write('												0 : 이미지가 작으면 이미지를 도면크기에 맞추고 이미지가 크면 원래 크기로 보여줌(기본값)');
document.write('												1 : 이미지를 도면파일의 크기에 맞게 확대/축소함');
document.write('												2 : 이미지를 확대/축소하지 않고 원래 크기로 보여줌');
document.write('												-->');
document.write('	<PARAM NAME="UseCombineImageScale" VALUE=1>	<!-- Combine 도면의 image size를 image의 scale 정보를 이용할지 여부');
document.write('												0 : dwg 파일의 image scale 정보 무시');
document.write('												1 : dwg 파일에 image scale 정보가 있으면 scale로 보이게 함(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="ZoomObjectLevel" VALUE=6>		<!-- ZoomText(), ZoomBlock() 등 특정 Object를 Zoom in 하는 경우 어느 정도로 확대를 할지 여부');
document.write('												6 : 기본값');
document.write('												1 ~ 500 : 작을수록 Object가 화면에 꽉차게 크게 보이며 클수록 Object가 작고 배경이 크게 보임');
document.write('												-->');
document.write('	<PARAM NAME="ZoomAreaLevel" VALUE=28>		<!-- ZoomArea() Method에서 특정 Area를 Zoom in 하는 경우 어느 정도로 확대를 할지 여부');
document.write('												28 : 기본값');
document.write('												1 ~ 500 : 작을수록 Area가 화면에 꽉차게 크게 보이며 클수록 Area가 작고 배경이 크게 보임');
document.write('												-->');
document.write('	<PARAM NAME="ZoomAllClick" VALUE=1>			<!-- Zoom cursor에서 화면 클릭 시 전체보기로 전환을 할지 여부');
document.write('												0 : 전환하지 않기');
document.write('												1 : 전환하기(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="HelpFile" VALUE="">			<!-- 도움말 보기 메뉴(또는 툴바 버튼)을 눌렀을 때 보여줄 도움말 경로 지정');
document.write('												"" : default 도움말을 보여줌(기본값)');
document.write('												"xxx" : xxx 파일을 보여줌');
document.write('												-->');
document.write('	<PARAM NAME="DisablePrintScreen" VALUE=1>	<!-- PrintScreen Key Enable/Disable 여부');
document.write('												0 : Enable');
document.write('												1 : Disable(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="SaveScreenShotToolbarEnable" VALUE=1>	<!-- SaveScreenShot 툴바 기능 유무');
document.write('														0 : Disable');
document.write('														1 : Enable(기본값)');
document.write('														-->');
document.write('	<PARAM NAME="BlockProcessList" VALUE="">	<!-- 프로그램을 등록하면 XRapidView 실행 중 등록된 Process를 강제 종료 시킴');
document.write('												(복수의 프로세스를 추가하려면 ";"을 구분자로 사용)');
document.write('												"" : (기본값), ex : "hsdx.exe;snagit32.exe"');
document.write('												-->');
document.write('	<PARAM NAME="PickerEventMode" VALUE=0>		<!-- Picker Cursor에서 겹쳐있는 Block과 Text Object Click 시 Event 발생 Mode');
document.write('												0 : TextSelected, BlockSelected Event 모두 발생(기본값)');
document.write('												1 : Text 우선, TextSelected Event만 발생');
document.write('												2 : Block 우선, BlockSelected Event만 발생');
document.write('												-->');
document.write('	<PARAM NAME="PickerMultiMode" VALUE=0>		<!-- Picker Cursor에서 마우스 Drag를 통하여 영역을 지정할 수 있게 할지 여부 설정');
document.write('												0 : 마우스 Drag를 통하여 영역을 지정할 수 없음(기본값)');
document.write('												1 : 마우스 Drag를 통하여 영역을 지정할 수 있음');
document.write('												-->');
document.write('	<PARAM NAME="PenTableMode" VALUE=1>			<!-- PenTable 설정을 LineWeight 설정시에 화면상에도 적용할지 여부');
document.write('												0 : 인쇄시에만 적용');
document.write('												1 : LineWeight 설정시에는 화면상에도 적용(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="ZoomRatio" VALUE=160>			<!-- 툴바 버튼으로 Zoom In/Out 시 확대/축소 비율');
document.write('												160 : 기본값');
document.write('												-->');
document.write('	<PARAM NAME="WheelRatio" VALUE=160>			<!-- 마우스 Wheel을 이용하여 Zoom In/Out 시 확대/축소 비율');
document.write('												160 : 기본값');
document.write('												-->');
document.write('	<PARAM NAME="ZoomExtentsRatio" VALUE=100>	<!-- ZoomExtents 시 화면에 맞게 확대/축소할 기준 비율');
document.write('												100 : 기본값');
document.write('												-->');
document.write('	<PARAM NAME="MarkupFontMinRatio" VALUE=0>	<!-- Markup 글꼴 설정시 도면 크기에 따라 계산된 표준 크기 대비 최소값의 비율(0 ~ 100 사이의 값)');
document.write('												0 이면 최소값 제한이 없으며 20 이면 표준 크기의 20% 이하면 20%로 설정됨');
document.write('												0 : 기본값');
document.write('												-->');
document.write('	<PARAM NAME="SupportFileType" VALUE="dwg;tif;jpg;gif">		<!-- File Type을 등록하면 XRapidView가 File Open시 등록 안된 File Type일 경우 Open 시도 자체를 하지 않음');
document.write('																아무 것도 등록하지 않으면 모든 File Type에 대해서 Open 시도를 하고 Open 할 수 없는 파일일 경우 잘못된 형식의 파일이라는 메세지를 띄우나');
document.write('																등록하면 등록된 File Type에 대해서만 Open 시도를 하고 Open 할 수 없는 경우 메세지를 띄우며 등록 안된 File Type에 대해서는 메세지 자체를 안띄움');
document.write('																(복수의 File Type를 추가하려면 ";"을 구분자로 사용)');
document.write('																"" : (기본값), ex : "dwg;dxf;tif;tiff;cg4;brw;brk;bmp;dib;cal;ras;cals;cif;clp;cut;pal;dcx;eps;epi;epsf;gif;ico;iff;img;ica;jpg;jpeg;pntg;mac;msp;pbm;pcd;pcx;pgm;pict;pct;png;pnm;ppm;psd;8pbs;rle;sgi;tga;tpic;txt;wmf;wpg;xbm;bm;bitmap;xpm;wd;g4;xwd"');
document.write('																-->');
document.write('	<PARAM NAME="FillText" VALUE=1>				<!-- 텍스트 외곽선만 보이기 -->');
document.write('	<PARAM NAME="AliasStyle" VALUE=3>			<!-- AliasStyle :');
document.write('												None = 0,');
document.write('												Preserve Black = 1,');
document.write('												Scale to Gray = 2,');
document.write('												Preserve White = 3');
document.write('												-->');
document.write('	<PARAM NAME="EntitySelectType" VALUE=2>		<!-- EntitySelectType :');
document.write('												EXTENT_AREA = 1, (영역방식)');
document.write('												DIRECT_ENTITY = 2(직접선택방식)');
document.write('												or 연산으로 사용');
document.write('												-->');
document.write('	<PARAM NAME="ExtractTextInfo" VALUE=0>		<!-- dwg file Open 시 Text 정보를 추출할지 여부(기본값 : 1) -->');
document.write('	<PARAM NAME="ExtractBlockInfo" VALUE=1>		<!-- dwg file Open 시 Block 정보를 추출할지 여부(기본값 : 1),블록 속성추출 -->');
document.write('	<PARAM NAME="ExtractBlockInfo2" VALUE=1>	<!-- dwg file Open 시 Block 정보를 추출할지 여부(기본값 : true), 모든 블록 ID 추출 -->');
document.write('	<PARAM NAME="HasMarkupToolbar" VALUE=1>		<!-- Markup 툴바 보여줄지 여부(보기:1, 안보기:2, 기본값:1'); 
document.write('												UIMode에 UIMODE_TOOLBAR(값:2)이 우선');
document.write('												-->');
document.write('	<PARAM NAME="AcadDblBuffer" VALUE=true>		<!-- dwg 를 더블버퍼 방식으로 그리기 여부(기본값 : true)-->');
document.write('	<PARAM NAME="ToolbarHasTooltip" VALUE=1>	<!-- 툴바 툴팁 표시여부 (0:표시안함, 1:표시, 기본값 : 1)-->');
document.write('	<PARAM NAME="LineWeight" VALUE=1>			<!-- 선가중치관련-->');
document.write('	<PARAM NAME="FixFontColor" VALUE=0>			<!-- 글꼴색고정관련 (0:고정안함, 1:고정(검정색), 기본값 : 0)-->');
document.write('	<PARAM NAME="MainToolbartype" VALUE=2>		<!-- 메인 툴바 타입(0:기본, 1:오일뱅크용 2:ScreenShot추가툴바) (기본값 : 0)-->');
document.write('	<PARAM NAME="MarkupSaveType" VALUE=1>		<!-- 마크업 저장 타입(0:기본, 1:저장경로입력창 2:저장경로입력창(저장파일명받아서 Default파일명지정)) (기본값 : 0)-->');
document.write('	<PARAM NAME="MarkupFileName" VALUE="">		<!-- 마크업 저장 타입이 2(저장경로입력창(저장파일명받아서 Default파일명지정))일경우 파일명 지정. (기본값 : "", NULL)-->');
document.write('	<PARAM NAME="StylePath" VALUE="C:\\Program Files (x86)\\OpenMinds\\XRapidView\\Font">		<!-- StylePath ctb파일경로를 지정.(인쇄설정에서쓰임) (기본값 : "") -->');
document.write('	<PARAM NAME="UsePrintPreviewImageSave" VALUE=1>		<!-- 인쇄 미리보기시 비트맵 이미지 적용 여부 설정 (0:기존 GDI방식 사용, 1:비트맵 사용, 기본값 : 1)-->');
document.write('	<PARAM NAME="DeviceModule" VALUE=1>			<!-- DeviceModule :');
document.write('												WinGDI = 0,');
document.write('												OpenGL = 1(기본값)');
document.write('												-->');
document.write('	<PARAM NAME="ToolbarIconSize" VALUE=32>		<!-- Toolbar Icon Size 지정(16, 32)');
document.write('												16 : 16X16 크기의 아이콘 표시(기본값)');
document.write('												32 : 32X32 크기의 아이콘 표시');
document.write('												-->');
document.write('</OBJECT>');
